// HTMLLinkElement对象
HTMLLinkElement = function HTMLLinkElement(){return hahavm.toolsFunc.throwError("TypeError", "Illegal constructor")}
hahavm.toolsFunc.safeProto(HTMLLinkElement, "HTMLLinkElement");
Object.setPrototypeOf(HTMLLinkElement.prototype, HTMLElement.prototype);
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "disabled", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "disabled_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "disabled_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "href", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "href_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "href_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "crossOrigin", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "crossOrigin_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "crossOrigin_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "rel", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "rel_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "rel_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "relList", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "relList_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "relList_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "media", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "media_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "media_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "hreflang", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "hreflang_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "hreflang_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "type", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "type_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "type_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "as", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "as_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "as_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "referrerPolicy_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "referrerPolicy_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "sizes", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "sizes_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "sizes_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "imageSrcset", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "imageSrcset_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "imageSrcset_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "imageSizes", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "imageSizes_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "imageSizes_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "charset", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "charset_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "charset_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "rev", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "rev_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "rev_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "target", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "target_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "target_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "sheet", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "sheet_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "integrity", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "integrity_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "integrity_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "fetchPriority", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "fetchPriority_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "fetchPriority_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLLinkElement.prototype, "blocking", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "blocking_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLLinkElement.prototype, "HTMLLinkElement", "blocking_set", arguments)}});
