// HTMLIFrameElement对象
HTMLIFrameElement = function HTMLIFrameElement(){return hahavm.toolsFunc.throwError("TypeError", "Illegal constructor")}
hahavm.toolsFunc.safeProto(HTMLIFrameElement, "HTMLIFrameElement");
Object.setPrototypeOf(HTMLIFrameElement.prototype, HTMLElement.prototype);
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "src", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "src_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "src_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "srcdoc", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "srcdoc_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "srcdoc_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "name", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "name_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "name_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "sandbox", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "sandbox_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "sandbox_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "allowFullscreen", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "allowFullscreen_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "allowFullscreen_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "width", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "width_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "width_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "height", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "height_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "height_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "contentDocument", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "contentDocument_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "contentWindow", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "contentWindow_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "referrerPolicy_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "referrerPolicy_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "csp", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "csp_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "csp_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "allow", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "allow_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "allow_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "featurePolicy", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "featurePolicy_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "align", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "align_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "align_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "scrolling", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "scrolling_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "scrolling_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "frameBorder", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "frameBorder_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "frameBorder_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "longDesc", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "longDesc_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "longDesc_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "marginHeight", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "marginHeight_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "marginHeight_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "marginWidth", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "marginWidth_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "marginWidth_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "getSVGDocument", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "getSVGDocument", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "loading", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "loading_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "loading_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "allowPaymentRequest", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "allowPaymentRequest_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "allowPaymentRequest_set", arguments)}});
