// HTMLButtonElement对象
HTMLButtonElement = function HTMLButtonElement(){return hahavm.toolsFunc.throwError("TypeError", "Illegal constructor")}
hahavm.toolsFunc.safeProto(HTMLButtonElement, "HTMLButtonElement");
Object.setPrototypeOf(HTMLButtonElement.prototype, HTMLElement.prototype);
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "disabled", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "disabled_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "disabled_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "form", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "form_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formAction", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formAction_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formAction_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formEnctype", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formEnctype_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formEnctype_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formMethod", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formMethod_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formMethod_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formNoValidate", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formNoValidate_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formNoValidate_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formTarget", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formTarget_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "formTarget_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "name", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "name_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "name_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "type", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "type_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "type_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "value", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "value_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "value_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "willValidate", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "willValidate_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "validity", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "validity_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "validationMessage", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "validationMessage_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "labels", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "labels_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "checkValidity", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "reportValidity", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "setCustomValidity", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "setCustomValidity", arguments)}});
