// HTMLFormElement对象
HTMLFormElement = function HTMLFormElement(){return hahavm.toolsFunc.throwError("TypeError", "Illegal constructor")}
hahavm.toolsFunc.safeProto(HTMLFormElement, "HTMLFormElement");
Object.setPrototypeOf(HTMLFormElement.prototype, HTMLElement.prototype);
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "acceptCharset", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "acceptCharset_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "acceptCharset_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "action", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "action_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "action_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "autocomplete", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "autocomplete_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "autocomplete_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "enctype", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "enctype_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "enctype_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "encoding", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "encoding_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "encoding_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "method", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "method_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "method_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "name", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "name_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "name_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "noValidate", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "noValidate_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "noValidate_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "target", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "target_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "target_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "elements", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "elements_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "length", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "length_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "checkValidity", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "reportValidity", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "requestSubmit", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "requestSubmit", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "reset", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "reset", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "submit", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "submit", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "rel", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "rel_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "rel_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLFormElement.prototype, "relList", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "relList_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLFormElement.prototype, "HTMLFormElement", "relList_set", arguments)}});
