// HTMLAreaElement对象
HTMLAreaElement = function HTMLAreaElement(){return hahavm.toolsFunc.throwError("TypeError", "Illegal constructor")}
hahavm.toolsFunc.safeProto(HTMLAreaElement, "HTMLAreaElement");
Object.setPrototypeOf(HTMLAreaElement.prototype, HTMLElement.prototype);
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "alt", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "alt_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "alt_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "coords", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "coords_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "coords_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "download", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "download_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "download_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "shape", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "shape_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "shape_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "target", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "target_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "target_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "ping", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "ping_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "ping_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "rel", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "rel_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "rel_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "relList", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "relList_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "relList_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "referrerPolicy_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "referrerPolicy_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "noHref", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "noHref_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "noHref_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "origin", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "origin_get", arguments)}, set:undefined});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "protocol", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "protocol_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "protocol_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "username", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "username_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "username_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "password", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "password_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "password_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "host", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "host_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "host_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "hostname", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "hostname_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "hostname_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "port", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "port_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "port_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "pathname", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "pathname_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "pathname_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "search", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "search_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "search_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "hash", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "hash_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "hash_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "href", {configurable:true, enumerable:true, get:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "href_get", arguments)}, set:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "href_set", arguments)}});
hahavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "toString", {configurable:true, enumerable:true, writable:true, value:function (){return hahavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "toString", arguments)}});
